#!/usr/bin/env bash
# The boot menu: limine's own settings, and the snapshot entries. CHOICES.md
# `snapshot-boot-entries`, `kernel-boot-entries`.
#
# Three things, and the third is the one that needs care.
#
# 1. /etc/default/limine — `FIND_BOOTLOADERS=no`. Upstream's own instruction is to
#    override here rather than edit the pacman-owned
#    /etc/limine-entry-tool.conf. The ESP fallback loader on this machine is
#    limine, so the auto-discovered "EFI fallback" entry chainloads the menu you
#    are already looking at.
#
# 2. `limine-snapper-sync.service` enabled as a boot-time oneshot. With
#    `inotify-tools` absent it takes upstream's own fallback branch, prints
#    "Falling back to Snapper plugin integration" and exits — MainPID=0, nothing
#    resident. That is why the row could pick it at all.
#
# 3. limine.conf's top-level directives. Its path is found, not assumed
#    (scripts/find-limine-conf.sh), since archinstall nests it while a manual
#    install leaves it flat; see CHOICES.md `bootloader`. The file is not
#    package-owned and is rewritten by limine-entry-tool and limine-snapper-sync
#    as kernels and snapshots come and go, but the header directives survive
#    that. It is also the file that took this machine off the network once
#    (benchmarks/4.24), so it is backed up before any edit and validated by
#    scripts/check-limine.sh afterwards.
#
# `default_entry` is set, and in the path form. Its default is 1, entry 1 here is
# the `Arch Linux` folder, and limine will not boot a folder — it forces the
# timeout off and waits for input forever. That is the 4.24 failure, and the only
# symptom was silence.
#
# The path form rather than the index, because the menu is regenerated by
# limine-entry-tool on every kernel change and limine-snapper-sync on every
# snapshot. An index survives only as long as nothing reorders the menu; a path
# names the same leaf forever, and limine's `find_entry_by_path()` matches only
# where `sub == NULL`, so it cannot resolve to a folder even in principle.
#
# If a machine's menu names things differently — a different kernel package, so not
# `linux` — this value names nothing, and scripts/check-limine.sh at the end of
# this step fails loudly rather than leaving an unbootable default.
#
# Idempotent; honours BUNNY_DRY_RUN.
#
# Usage: 50-limine.sh [--help]
set -Eeuo pipefail

case "${1-}" in
-h | --help)
	sed -n '2,/^set -/p' "$0" | sed 's|^# \?||;$d'
	exit
	;;
esac

say() { printf '%s\n' "$*" >&2; }
dry=${BUNNY_DRY_RUN:-}

# Converge on one limine, the one the tooling maintains. archinstall installs it
# to `$ESP/EFI/arch-limine/` with its config beside it. Every tool this repo
# depends on installs it somewhere else and cannot be told otherwise —
# /usr/lib/limine/limine-common-functions hardcodes
#
#     LIMINE_EFI_PATH="\\EFI\\limine\\${LIMINE_EFI_FILE}"
#     LIMINE_CONFIG_PATH="${ESP_PATH}/limine.conf"
#
# so `limine-entry-tool`, `limine-snapper-sync` and `limine-mkinitcpio-hook` all
# read and write `$ESP/limine.conf` with the binary at `$ESP/EFI/limine/`.
#
# Leaving both in place is the worst outcome, and it is what a fresh install
# produces: found 2026-08-28 with `BootCurrent` on archinstall's copy while
# `BootOrder` led with the tooling's, so the next boot would have read a
# limine.conf no kernel update had ever touched. Snapshot and new-kernel entries
# land in the tooling's file; archinstall's is written once and goes stale.
#
# So archinstall's copy is removed once the tooling's exists. The order matters:
# 20-packages.sh installs `limine-mkinitcpio-hook`, whose first run deploys
# `EFI/limine/` and registers its own boot entry, so by now both are present.
esp=$(findmnt -no TARGET /boot)
if sudo test -f "$esp/limine.conf" && sudo test -f "$esp/EFI/limine/limine_x64.efi"; then
	for stale in "$esp"/EFI/arch-limine "$esp"/EFI/ARCH-LIMINE; do
		[[ -d $stale ]] || continue
		if [[ -n $dry ]]; then
			say "  ~ would remove archinstall's orphaned $stale"
			continue
		fi
		sudo rm -rf -- "$stale"
		say "  + removed archinstall's orphaned $stale"
	done
	# ...and the firmware entry that points into it, or the machine still boots
	# the copy whose files have just been deleted.
	while read -r num; do
		[[ -n $num ]] || continue
		if [[ -n $dry ]]; then
			say "  ~ would remove boot entry $num (points at the removed arch-limine)"
			continue
		fi
		sudo efibootmgr -b "$num" -B >/dev/null
		say "  + removed boot entry $num (pointed at the removed arch-limine)"
	done < <(sudo efibootmgr -v 2>/dev/null |
		grep -iE "^Boot[0-9A-F]{4}\\*?.*[\\\\/]EFI[\\\\/]ARCH-LIMINE[\\\\/]" |
		sed -E 's/^Boot([0-9A-Fa-f]{4}).*/\1/')
elif [[ -z $dry ]]; then
	say "  ! $esp/limine.conf or $esp/EFI/limine/limine_x64.efi is missing"
	say "    limine-mkinitcpio-hook deploys both; without them nothing maintains"
	say "    the boot menu and snapshot entries would go to a file limine never reads."
	exit 1
fi

# Under sudo: archinstall's ESP mount (fmask=0077,dmask=0077) makes /boot
# root-only, and everything else in this step already escalates.
finder="${BUNNY_ROOT:-}/scripts/find-limine-conf.sh"
if [[ ! -x $finder ]]; then
	say "  ! scripts/find-limine-conf.sh not found at $finder"
	exit 1
fi
LCONF=$(sudo "$finder") || {
	say "  ! could not locate limine.conf -- is limine installed?"
	exit 1
}
readonly LCONF

# 1. /etc/default/limine.
read -r -d '' default_limine <<'EOF' || true
# Bunny deviations from /etc/limine-entry-tool.conf. Upstream says override here,
# not by editing that pacman-owned file.
#
# The ESP fallback loader (/EFI/BOOT/BOOTX64.EFI) IS limine on this machine, so the
# auto-discovered "EFI fallback" entry chainloads the menu you are already looking at.
FIND_BOOTLOADERS=no

# ENABLE_UKI=yes reverses the non-UKI decision in CHOICES.md
# `snapshot-boot-entries` (split vmlinuz+initramfs was picked there for
# per-kernel-build ESP dedup across snapshots). Author, 2026-09-02: the
# Plymouth password dialog is a static image that never updates per
# keystroke, on both the bunny theme and the stock `script` theme --
# confirmed theme-independent, so not a `bunny.script` bug -- and
# viacoffee/dotfiles (identical Framework 13 AMD hardware, confirmed working)
# boots a UKI where this repo boots split images. Every other lever tried
# (mkinitcpio HOOKS= order, boot-artifact staleness) is now ruled out; this is
# the last unreplicated structural difference. Traded in knowingly, not
# proven as the mechanism -- if it doesn't fix it, revert this line first.
ENABLE_UKI=yes
EOF

if [[ -f /etc/default/limine ]] && [[ $(cat /etc/default/limine) == "$default_limine" ]]; then
	say "  = /etc/default/limine already correct"
elif [[ -n $dry ]]; then
	say "  ~ would write /etc/default/limine (FIND_BOOTLOADERS=no)"
else
	sudo install -Dm644 /dev/stdin /etc/default/limine <<<"$default_limine"
	say "  + wrote /etc/default/limine"
fi

# 2. The sync unit.
if [[ $(systemctl is-enabled limine-snapper-sync.service 2>/dev/null || true) == enabled ]]; then
	say "  = limine-snapper-sync.service enabled"
elif [[ -n $dry ]]; then
	say "  ~ would enable limine-snapper-sync.service"
else
	sudo systemctl enable limine-snapper-sync.service
	say "  + enabled limine-snapper-sync.service"
fi

# 3. The top-level directives.
#
# `timeout: 3` costs 2 s on every boot, measured (benchmarks/4.28, n=3/arm) and
# accepted knowingly: priority 1 outranks 2a, and a one-second window is only
# catchable if you are already expecting it.
#
# `hash_mismatch_panic: no` is wholly unexercised — it acts only on a hash
# mismatch and there has never been one here. Proving it means corrupting a boot()
# file on the ESP with no remote power control if it goes wrong.
#
# An indexed array, not an associative one: bash gives no order guarantee for
# `${!assoc[@]}`, and since each missing directive is inserted at line 1 the
# iteration order became the file order, so two machines got byte-different
# limine.conf files meaning the same thing.
#
# `default_entry` is derived, not hardcoded. It used to be the literal
# `Arch Linux/linux`, the path form for a nested entry, which is what
# `limine-mkinitcpio-hook` generates once it has regenerated the menu. But a
# freshly installed machine has archinstall's own flat `/Arch Linux (linux)`, so
# the hardcoded value named nothing and this step failed on every fresh install.
# Both shapes are real and the file changes underneath us, so the value is read
# out of the file each run by the checker's own parser — one parser, so a default
# this writes cannot be one the check would reject.
default_entry=$(sudo bash "${BUNNY_ROOT:?run me through install.sh}/scripts/check-limine.sh" --default-path "$LCONF")
[[ -n $default_entry ]] || {
	say "  ! no bootable entry found in $LCONF — refusing to guess at default_entry"
	exit 1
}
readonly WANT=('timeout: 1' 'hash_mismatch_panic: no' "default_entry: $default_entry")

backed_up=false
# Reverse order, because each insert goes to line 1: inserting the last wanted
# directive first leaves them in WANT's order in the file.
for ((i = ${#WANT[@]} - 1; i >= 0; i--)); do
	directive=${WANT[i]}
	key=${directive%%:*}
	if sudo grep -qxF "$directive" "$LCONF"; then
		say "  = $directive"
		continue
	fi
	if [[ -n $dry ]]; then
		say "  ~ would set '$directive' in $LCONF"
		continue
	fi
	# One backup per run, before the first change, because this is the file that
	# took the machine off the network in 4.24.
	if ! $backed_up; then
		sudo cp -a "$LCONF" "$LCONF.bunny-install.bak"
		say "  + backed up $LCONF -> $LCONF.bunny-install.bak"
		backed_up=true
	fi
	if sudo grep -qE "^$key:" "$LCONF"; then
		sudo sed -i "s|^$key:.*|$directive|" "$LCONF"
	else
		sudo sed -i "1i $directive" "$LCONF"
	fi
	sudo grep -qxF "$directive" "$LCONF" || {
		say "  ! could not set '$directive'"
		exit 1
	}
	say "  + $directive"
done

if [[ -n $dry ]]; then exit 0; fi

# Validate with the repo's own checker: limine ships none, which is why
# scripts/check-limine.sh exists. One place knows what a broken limine.conf
# looks like.
checker="${BUNNY_ROOT:-}/scripts/check-limine.sh"
# Not optional and not a warning: this repo ships that script, so its absence
# means a broken checkout, and carrying on would mean having just rewritten the
# boot configuration with nothing confirming the machine can still boot.
[[ -x $checker ]] || {
	say "  ! scripts/check-limine.sh not found at $checker"
	say "    The boot config was just modified and cannot be validated."
	say "    Restore the checkout before rebooting."
	exit 1
}
sudo "$checker" "$LCONF" >/dev/null || {
	say "  ! scripts/check-limine.sh rejected $LCONF — run it directly for detail"
	exit 1
}
say "  ✓ check-limine.sh passes"
