#!/usr/bin/env bash
# List the files in /etc that no package owns — everything Bunny or a human put
# there, which is exactly the set install.sh has to reproduce.
#
# docs/phase4-config-inventory.md was built from `pacman -Qkk` plus a hand check
# of the paths CHOICES.md rows happen to name, and it missed three files.
# `pacman -Qkk` reports package-owned files that differ from what shipped; a file
# no package owns at all is invisible to it. The method here asks the opposite
# question — not "are the files I know about correct" but "what is here that I do
# not know about" — as a set difference between what pacman owns and what is on
# disk.
#
# Data (the paths) to stdout, counts and headings to stderr, so this can be
# diffed against a previous run or fed to a loop.
#
# Usage: check-unowned-etc.sh [--all] [--help]
#   --all   skip the noise filter and print every unowned path
set -Eeuo pipefail

all=false
case "${1-}" in
--all) all=true ;;
-h | --help)
	sed -n '2,/^set -/p' "$0" | sed 's|^# \?||;$d'
	exit
	;;
'') ;;
*)
	echo "unknown: $1" >&2
	exit 1
	;;
esac

command -v pacman >/dev/null || {
	echo "pacman not found -- this check only means anything on Arch" >&2
	exit 1
}

owned=$(mktemp)
present=$(mktemp)
errs=$(mktemp)
trap 'rm -f "$owned" "$present" "$errs"' EXIT

# `pacman -Qlq` lists directories with a trailing slash; strip it so directory
# entries cannot masquerade as files and hide a real path behind them.
pacman -Qlq | grep '^/etc/' | sed 's|/$||' | sort -u >"$owned"

# `find` exits nonzero on any directory it cannot read, and as a normal user under
# /etc there is at least one (pacman's gnupg private keys). Discarding that status
# would mean discarding files, so the unreadable paths get named instead.
find /etc \( -type f -o -type l \) 2>"$errs" | sort -u >"$present" || true
if [[ -s $errs ]]; then
	echo "WARNING: $(wc -l <"$errs") path(s) under /etc unreadable as $(id -un);" >&2
	echo "         anything inside them is NOT in the list below. Re-run with" >&2
	echo "         sudo for a complete survey." >&2
	sed 's/^/         /' "$errs" >&2
fi

total=$(comm -13 "$owned" "$present" | wc -l)
echo "unowned paths under /etc: $total" >&2

if $all; then
	comm -13 "$owned" "$present"
	exit
fi

# The noise filter. Every entry is a category, not a path — a filter listing
# individual files would quietly hide the next new one. One `grep` rather than a
# chain, because under `pipefail` any link that matches nothing exits 1 and kills
# the whole pipeline.
noise=(
	# generated caches and state -- nobody chose these
	'^/etc/(ld\.so\.cache|\.pwd\.lock|\.updated|adjtime|os-release|udev/hwdb\.bin)$'
	# machine identity, deliberately untracked (inventory section 4). The
	# trailing `-` forms are shadow(5)'s own backups of the same files.
	'^/etc/(passwd|shadow|group|gshadow|subuid|subgid)-?$'
	'^/etc/(machine-id|hostname|hosts|resolv\.conf|shells|locale\.conf|vconsole\.conf|localtime|fstab|crypttab|mtab)$'
	# written by package hooks, and keyring/cert state. `mkinitcpio.d/*.preset`
	# is generated by mkinitcpio's own pacman hook from
	# /usr/share/mkinitcpio/hook.preset, which is why no package owns it.
	# (prefix match -- these are whole trees of generated files)
	'^/etc/(ssl/certs|ca-certificates|pacman\.d/gnupg|ssh/ssh_host|texmf/(ls-R|web2c/updmap\.cfg))'
	'^/etc/mkinitcpio\.d/.*\.preset$'
	# `systemctl enable` bookkeeping
	'^/etc/systemd/(system|user)/.*\.wants/'
	# written by fontconfig's own hook
	'^/etc/fonts/conf\.d/'
	# transient
	'\.(pacnew|pacsave|bak|old)$'
)
re=$(
	IFS='|'
	echo "${noise[*]}"
)

comm -13 "$owned" "$present" | { grep -vE "$re" || true; } |
	while IFS= read -r p; do
		# A symlink into /usr/lib/systemd is `systemctl enable`'s work (an Alias= in
		# the unit), not a file anyone authored.
		if [[ -L $p && $(readlink -f "$p") == /usr/lib/systemd/* ]]; then
			continue
		fi
		printf '%s\n' "$p"
	done
